import img1 from './img1.png';
import img2 from './img2.png';
import img3 from './img3.png';
import img4 from './img4.png';
import img5 from './img5.png';
import img6 from './img6.png';
import img7 from './img7.png';
import img8 from './img8.png';
import img9 from './img9.png';
import img10 from './img10.png';
import img1_1 from './img1-1.png';
import img2_1 from './img2-1.png';
import img3_1 from './img3-1.png';
import img4_1 from './img4-1.png';
import img5_1 from './img5-1.png';
import img7_1 from './img7-1.png';
import img10_1 from './img10-1.png';
import img1_2 from './img1-2.png';
import img2_2 from './img2-2.png';
import img3_2 from './img3-2.png';
import img4_2 from './img4-2.png';
import img5_2 from './img5-2.png';
import img7_2 from './img7-2.png';

export const dataServices = [
    {
        id: 1,
        image: img1,
        image1: img1_2,
        image2: img1_1,
        header: `Body myostimulation`,
        header2: 'Recommended for:',
        header3: 'Contraindications:',
        line1: `1 session - $ 45`,
        line1Crossed: ``,
        line2: `5 sessions - $ 200`,
        line2Crossed: `$ 225`,
        line3: `10 sessions - $ 400`,
        line3Crossed: `$ 450`,
        searchTerm: 'body',
        learnMoreTxt1: `Myostimulation is a procedure, the essence of which is in the impact of impulse currents on muscles, internal organs and the nervous system, restoring and improving their work. With this method, you can noticeably lose weight or, conversely, increase muscle mass.
        This method is a great alternative to various physical activities.`,
        ulRecommended: [
            {li: 'sagging muscles and skin;'},
            {li: 'overweight;'},
            {li: 'cellulite;'},
            {li: 'venous disorders;'},
            {li: 'venous-lymphatic insufficiency.'},
        ],
        ulContradications: [
            {li: 'pregnancy;'},
            {li: 'active tuberculosis of the lungs and kidneys;'},
            {li: 'thrombophlebitis;'},
            {li: 'urolithiasis, cystitis;'},
            {li: 'cholelithiasis;'},
            {li: 'purulent inflammatory processes;'},
            {li: 'kidney and liver failure;'},
            {li: 'skin diseases;'},
            {li: 'implant devices such as pacemakers or electrical prosthesis.'},
        ],
    },

    {
        id: 2,
        image: img2,
        image1: img2_2,
        image2: img2_1,
        header: `Face myostimulation`,
        header2: 'The effect of the procedure:',
        header3: 'Contraindications:',
        line1: `10 sessions - $ 500`,
        line1Crossed: `$ 600`,
        line2: ``,
        line2Crossed: ``,
        line3: ``,
        line3Crossed: ``,
        searchTerm: 'face',
        learnMoreTxt1: `An effective procedure for tightening the facial muscles with the help of pulsed electric current. After the procedure, the contour of your face will become clear, your cheekbones will be more expressive, and your skin will be toned and elastic.`,
        ulRecommended: [
            {li: 'facial contour improves;'},
            {li: 'cellulite reducer;'},
            {li: 'cheekbones become more pronounced;'},
            {li: 'the face skin looks more toned and dense;'},
            {li: 'the second chin decreases or completely disappears.'},
        ],
        ulContradications: [
            {li: 'pregnancy;'},
            {li: 'implant devices such as pacemakers or electrical prosthesis;'},
            {li: 'the presence of subcutaneous implants;'},
            {li: 'periods;'},
            {li: 'oncological diseases;'},
            {li: 'infectious diseases, including tuberculosis;'},
            {li: 'insufficiency of liver and kidney function;'},
            {li: 'epilepsy'},
        ],
    },

    {
        id: 3,
        image: img3,
        image1: img3_2,
        image2: img3_1,
        header: `Body/Face RF lifting`,
        header2: 'Recommended for:',
        header3: 'Contraindications:',
        line1: `1 session - $ 100`,
        line1Crossed: ``,
        line2: `4 sessions - $ 360`,
        line2Crossed: `$ 400`,
        line3: `8 sessions - $ 700`,
        line3Crossed: `$ 800`,
        searchTerm: 'body', 
        learnMoreTxt1: `With age, collagen production decreases, the skin becomes dry, flabby, and wrinkles appear. To cope with this scourge and helps the procedure of radio wave lifting. During this operation, high-frequency electric current is applied, which penetrates into the deep layers of the epidermis and stimulates the production of collagen.`,
        ulRecommended: [
            {li: 'age-related change in the oval of the face;'},
            {li: 'the presence of deep mimic wrinkles;'},
            {li: 'photoaging and dry skin;'},
            {li: 'loss of skin tone and wilting.'},
        ],
        ulContradications: [
            {li: 'high skin sensitivity and a tendency to allergic reactions;'},
            {li: 'a large number of moles and age spots;'},
            {li: 'under eye bags and drooping eyelids;'},
            {li: 'atherosclerosis and diseases of the nervous system;'},
            {li: 'acute and chronic skin diseases;'},
            {li: 'oncology;'},
            {li: 'hypertension.'},
        ],
    },

    {
        id: 4,
        image: img4,
        image1: img4_2,
        image2: img4_1,
        header: `Pressotherapy`,
        header2: 'Recommended for:',
        header3: 'Contraindications:',
        line1: `1 session - $ 35`,
        line1Crossed: ``,
        line2: `5 sessions - $ 120`,
        line2Crossed: `$ 175`,
        line3: `10 sessions - $ 280`,
        line3Crossed: `$ 350`,
        searchTerm: 'body',
        learnMoreTxt1: `Hardware lymphatic drainage that has an effect
        on the human lymphatic system using compressed air, which is supplied through a special suit. Equipment
        for this procedure was created taking into account all anatomical features and human physiology.`,
        ulRecommended: [
            {li: 'cellulite;'},
            {li: 'leg spasms;'},
            {li: 'swelling;'},
            {li: 'overweight;'},
            {li: 'decrease in skin elasticity;'},
            {li: 'chronic leg fatigue.'},
        ],
        ulContradications: [
            {li: 'thrombosis;'},
            {li: 'diseases of the cardiovascular system;'},
            {li: 'skin diseases;'},
            {li: 'sharp pain;'},
            {li: 'kidney failure.'},
        ],
    },

    {
        id: 5,
        image: img5,
        image1: img5_2,
        image2: img5_1,
        header: `Vacuum cupping massage`,
        header2: 'The recommended course is 10-20 sessions.',
        header3: 'Contraindications:',
        line1: `1 session - $ 45`,
        line1Crossed: ``,
        line2: `5 sessions - $ 200`,
        line2Crossed: `$ 225`,
        line3: `10 sessions - $ 400`,
        line3Crossed: `$ 450`,
        searchTerm: 'body',
        learnMoreTxt1: `If you decide to reduce your weight, correct body shape, improve skin condition and get rid of cellulite, vacuum cupping massage will help you.`,
        ulRecommended: [
            {li: 'reduce painful trigger points;'},
            {li: 'improve blood and lymph circulation;'},
            {li: 'relieve pain;'},
            {li: 'promote mobility and range of motion.'},
        ],
        ulContradications: [
            {li: 'acute inflammatory diseases of internal organs;'},
            {li: 'skin defects in the area of the intended impact;'},
            {li: 'thrombophlebitis;'},
            {li: 'cardiovascular diseases;'},
            {li: 'periods;'},
            {li: 'pregnancy and lactation;'},
            {li: 'malignant tumors.'},
        ],
    },

    {
        id: 6,
        image: img6,
        image1: img5_2,
        image2: img5_1,
        header: `Vacuum roller massage`,
        header2: 'Recommended for:',
        header3: 'Contraindications:',
        line1: `1 session - $ 60`,
        line1Crossed: ``,
        line2: `5 sessions - $ 250`,
        line2Crossed: `$ 300`,
        line3: `10 sessions - $ 500`,
        line3Crossed: `$ 600`,
        searchTerm: 'body',
        learnMoreTxt1: `If you decide to reduce your weight, correct body shape, improve skin condition and get rid of cellulite, vacuum roller massage will help you. In fact, this methodology models every part of your body step by step, reducing its volume and eliminating the risk of skin laxity during the period of active weight loss.`,
        ulRecommended: [
            {li: 'reduce painful trigger points;'},
            {li: 'improve blood and lymph circulation;'},
            {li: 'relieve pain;'},
            {li: 'promote mobility and range of motion.'},
        ],
        ulContradications: [
            {li: 'acute inflammatory diseases of internal organs;'},
            {li: 'skin defects in the area of the intended impact;'},
            {li: 'thrombophlebitis;'},
            {li: 'cardiovascular diseases;'},
            {li: 'pregnancy and lactation;'},
            {li: 'malignant tumors.'},
        ],
    },

    {
        id: 7,
        image: img7,
        image1: img7_2,
        image2: img7_1,
        header: `Eyelash lamination`,
        header2: 'Price:',
        header3: 'Advantages of lamination:',
        line1: `Removal - $ 20`,
        line1Crossed: ``,
        line2: `Extention - $ 100`,
        line2Crossed: ``,
        line3: `Lamination - $ 100`,
        line3Crossed: ``,
        searchTerm: 'eyelashes',
        learnMoreTxt1: `The main advantage of eyelash extensions is that you don’t need to spend time on makeup, applying mascara to the eyelashes takes a lot of time and you don’t always get a result that would be nice to see, you can also forget about worries about how the mascara doesn’t smear from the rain, the pool or tears, and no need to wash off persistent eye makeup in the evenings! The extension procedure is completely safe!`,
        ulRecommended: [
            {li: 'removal - $ 20;'},
            {li: 'lamination - $ 100;'},
            {li: 'extention (classic) - $ 100;'},
            {li: '2D extention - $ 180;'},
            {li: 'partial 2D extention - $ 130.'},
        ],
        ulContradications: [
            {li: 'eyelashes take on a new shape, acquiring a beautiful curve, even if you didn’t have it before;'},
            {li: 'a natural shine appears;'},
            {li: 'eyelash growth is significantly accelerated due to the activation of the bulbs;'},
            {li: 'the strength and thickness of the eyelashes increases;'},
            {li: 'the structure of the eyelashes regains its former strength, which was lost due to the use of cosmetics.'},
        ],
    },

    {
        id: 8,
        image: img8,
        image1: img8,
        image2: img7_2,
        header: `Eyebrow shaping and coloring`,
        header2: 'Price:',
        header3: 'Advantages of eyebrow shaping:',
        line1: `Art shaping & permanent coloring - $ 70`,
        line1Crossed: ``,
        line2: ``,
        line2Crossed: ``,
        line3: ``,
        line3Crossed: ``,
        searchTerm: 'eyelashes',
        learnMoreTxt1: `The main advantage of well-groomed eyebrows is that you do not need to spend time on makeup, you can also forget about worries about how the pencil would not be smeared from the rain or the pool, and you do not need to wash off persistent makeup in the evenings! The procedure is safe!`,
        ulRecommended: [
            {li: 'art shaping & permanent coloring - $ 70.'},
        ],
        ulContradications: [
            {li: 'accentuates your eyes. They say your eyes are the windows to your soul;'},
            {li: 'makes you look well-rested and younger;'},
            {li: 'lets you get away with a natural look;'},
            {li: 'Lifts your eyes without getting an actual eye lift.'},
        ],
    },

    {
        id: 9,
        image: img9,
        image1: img5_1,
        image2: img1_1,
        header: `Laser hair removal`,
        header2: 'Recommended for:',
        header3: 'Contraindications:',
        line1: `1 session - $ 60`,
        line1Crossed: ``,
        line2: `5 sessions - $ 250`,
        line2Crossed: `$ 300`,
        line3: `10 sessions - $ 500`,
        line3Crossed: `$ 600`,
        searchTerm: 'hair', 
        learnMoreTxt1: `During laser hair removal, a laser emits a light that is absorbed by the pigment (melanin) in the hair. The light energy is converted to heat, which damages the tube-shaped sacs within the skin (hair follicles) that produce hairs. This damage inhibits or delays future hair growth.`,
        ulRecommended: [
            {li: `it's quick`},
            {li: 'less painful than other hair removal methods'},
            {li: 'it prevents ingrown hairs.'},
            {li: 'it can remove hair from any part of the body'},
            {li: `it's a long-term solution.`},
        ],
        ulContradications: [
            {li: 'pregnancy;'},
            {li: 'breastfeeding;'},
            {li: 'medication;'},
            {li: 'sun tan;'},
            {li: 'dark skin;'},
            {li: 'keloid scarring;'},
            {li: 'tattoos.'},
        ],
    },

    {
        id: 10,
        image: img10,
        image1: img4_1,
        image2: img10_1,
        header: `Ultrasonic cavitation`,
        header2: 'Recommended for:',
        header3: 'Contraindications:',
        line1: `1 session - $ 50`,
        line1Crossed: ``,
        line2: `4 sessions - $ 150`,
        line2Crossed: `$ 200`,
        line3: `8 sessions - $ 300`,
        line3Crossed: `$ 400`,
        searchTerm: 'body',
        learnMoreTxt1: `Ultrasonic or ultrasound cavitation is the use of ultrasound technology to break down fat cells below the skin. It is a non-surgical method of reducing cellulite and localized fat. This procedure involves applying pressure on fat cells through ultrasonic vibrations.`,
        ulRecommended: [
            {li: 'cellulite and adipose fat;'},
            {li: 'body contouring;'},
            {li: 'quick results (vesible result after just one session).'},
        ],
        ulContradications: [
            {li: 'acute or contagious disease;'},
            {li: 'HIV;'},
            {li: 'a history of cancer;'},
            {li: 'kidney failure;'},
            {li: 'liver failure;'},
            {li: 'fatty liver;'},
            {li: 'implant devices such as pacemakers or electrical prosthesis;'},
            {li: 'epilepsy.'},
        ],
    }
]
